TARGET = "pronto_atendimento"

categorical_features = []

numerical_features = []

drop_features = [
    "record_id",
    "dt",
    "hora",
    "entrev",
    "domicilio",
    "endpdr",
    "idaderc",
    "sexorc",
    "recusa",
    "recusaout",
    "latitude",
    "longitude",
    "sexomor1",
    "idademor1",
    "trabmor1",
    "atforamor1",
    "sexomor2",
    "idademor2",
    "trabmor2",
    "atforamor2",
    "sexomor3",
    "idademor3",
    "trabmor3",
    "atforamor3",
    "sexomor4",
    "idademor4",
    "trabmor4",
    "atforamor4",
    "sexomor5",
    "idademor5",
    "trabmor5",
    "atforamor5",
    "sexomor6",
    "idademor6",
    "trabmor6",
    "atforamor6",
    "sexomor7",
    "idademor7",
    "trabmor7",
    "atforamor7",
    "sexomor8",
    "idademor8",
    "trabmor8",
    "atforamor8",
    "sexomor9",
    "idademor9",
    "trabmor9",
    "atforamor9",
    "sexomor10",
    "idademor10",
    "trabmor10",
    "atforamor10",
    "bairro",
    "cep",
    "dn",
    "osit",
    "horafim",
    "ende",
    "ACOMPANHAMENTO",
]

morbidades = [
    "ost",
    "art",
    "has",
    "diab",
    "pcor",
    "park",
    "rin",
    "tire",
    "glau",
    "cat",
    "alzh",
    "inc",
    "hepat",
    "dor",
    "out",
    "cancer",
    "dpoc",
    "enfs",
    "pros",
    "asm",
    "brq",
]

extras = [
    "depre_cut",
    "ansi_cut",
    "dep",
    "alc2",
    "fumo2",
    "obesidade",
    "asmbrq",
]

pronto_atendimento = [
    "aps",
    "aupaa",
    "aupab",
    "aubain",
    "aubail",
    "apau",
    "apas",
    "apah",
    "asamu",
    "aamp",
    "aout",
]

must_have_features = morbidades + extras + ["idade", "multi_calc"]

dtypes_dict = {}
